name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: nx-workspace
      - name: Build
        run: npx nx build shell --configuration=production
        working-directory: nx-workspace
      - name: Copy index.html to 404.html
        run: cp nx-workspace/dist/apps/shell/browser/index.html nx-workspace/dist/apps/shell/browser/404.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: nx-workspace/dist/apps/shell/browser